class MyErr: Exception

def f(x: Int) raise [MyErr] => print("nothing")
def g(x: Int) raise [MyErr] => f(x)
