def a := Exception()
def b := Exception("b")
