class Exception:
    def __init__(self, msg: str = ''): pass

    def __str__(self) -> str: pass
