a = Exception()
b = Exception("b")
